jasypt:
  encryptor:
    password: openbasketsecret
spring:
  datasource:
    url: jdbc:mysql://${ORDERS_DB_HOST:localhost}:${ORDERS_DB_PORT:3306}/${ORDERS_DB_NAME:ordersdb}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${ORDERS_DB_USER:root}
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${ORDERS_MAIL_ID:project.openbasket@gmail.com}
    password: ENC(U6sV6o0flVm5VYuj457AmN4j9JUfAbD2)
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

server:
  servlet:
    context-path: ${ORDERS_CONTEXT_PATH:/orders/v1}
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain,text/css,text/javascript

management:
  info:
    defaults:
      enabled: false
  endpoints:
    web:
      base-path: '/'
      exposure:
        include: metrics,health,refresh,info
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    refresh:
      enabled: true
    prometheus:
      enabled: true

stripe:
  private:
    key: ${STRIPE_SECRET_KEY:sk_test_51IL6YhCYSHJV743tsokBEqMmHt5JA9u42iLloHOQuPo03pYfCfv3suMeemJv5RXALwkg1PVCeV0mx3va24Gjn9Bx00PhLz22Io}
  success:
    url: ${STRIPE_SUCCESS_URL:http://localhost:4200/checkout/success}
  cancel:
    url: ${STRIPE_CANCEL_URL:http://localhost:4200/checkout/failure}
  currency: ${STRIPE_CURRENCY:gbp}



