spring:
  datasource:
    url: jdbc:mysql://${ORDERS_DB_HOST:cloud-sql-proxy}:${ORDERS_DB_PORT:3306}/${ORDERS_DB_NAME:sql-db}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${ORDERS_DB_USER:root}
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update