spring:
  cloud:
    gcp:
      sql:
        instance-connection-name: nodal-formula-295821:europe-west2:sql-instance
        database-name: sql-db
    appId: nodal-formula-295821
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
