spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:cloud-sql-proxy}:${DB_PORT:3306}/${DB_NAME:sql-db}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update